// <auto-generated />
using System;
using ApiGladsGo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ApiGladsGo.Migrations
{
    [DbContext(typeof(ApiGladsGoContext))]
    [Migration("20211113191329_carlosMara")]
    partial class carlosMara
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1");

            modelBuilder.Entity("ApiMySql.Data.Entities.Positions.Position", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(80);

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(4);

                    b.HasKey("Id");

                    b.ToTable("Positions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3ab5d4c6-adc2-439e-8993-24dbc82cbb7e"),
                            Name = "Wide Reciver",
                            ShortName = "WR"
                        },
                        new
                        {
                            Id = new Guid("3ed94c61-a398-47d6-9c82-641b1ddb1fd1"),
                            Name = "Quarterback",
                            ShortName = "QB"
                        },
                        new
                        {
                            Id = new Guid("dfd73943-b654-48fd-8d3f-bc35a2fcf19e"),
                            Name = "Running Back",
                            ShortName = "RB"
                        });
                });

            modelBuilder.Entity("ApiMySql.Data.Entities.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT")
                        .HasMaxLength(80);

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(80);

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(20);

                    b.Property<Guid>("PositionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PositionId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8035ab7f-a8e7-4c4b-a107-754b9d687c7d"),
                            Email = "Player1@gmail.com",
                            Name = "Player 1 ",
                            Password = "adm",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("3ab5d4c6-adc2-439e-8993-24dbc82cbb7e"),
                            Role = "adm"
                        },
                        new
                        {
                            Id = new Guid("e8776c22-794c-4b17-a7bd-33f2ad7cee79"),
                            Email = "Player2@gmail.com",
                            Name = "Player 2 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("3ed94c61-a398-47d6-9c82-641b1ddb1fd1"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("491673ca-b5fc-463c-806b-97bcf4e65e6d"),
                            Email = "Player3@gmail.com",
                            Name = "Player 3 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("dfd73943-b654-48fd-8d3f-bc35a2fcf19e"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("9b84e144-8f43-4a17-b608-b03fd512d270"),
                            Email = "Player4@gmail.com",
                            Name = "Player 4 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("dfd73943-b654-48fd-8d3f-bc35a2fcf19e"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("5b4862c1-5665-4c54-a54c-7b1a77099864"),
                            Email = "Player5@gmail.com",
                            Name = "Player 5 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("dfd73943-b654-48fd-8d3f-bc35a2fcf19e"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("a5e1043b-1ea3-4c3f-99df-415ad10ec130"),
                            Email = "Player6@gmail.com",
                            Name = "Player 6 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("3ed94c61-a398-47d6-9c82-641b1ddb1fd1"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("1e1f6d35-20db-49dc-83f1-6c31fbea4bdf"),
                            Email = "Player7@gmail.com",
                            Name = "Player 7 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("3ed94c61-a398-47d6-9c82-641b1ddb1fd1"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("92b345b7-dbf0-466b-910d-806d30caaa25"),
                            Email = "Player8@gmail.com",
                            Name = "Player 8 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("3ed94c61-a398-47d6-9c82-641b1ddb1fd1"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("df1bcd9f-70c4-4948-a67e-fc150817fe68"),
                            Email = "Player9@gmail.com",
                            Name = "Player 9 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("3ed94c61-a398-47d6-9c82-641b1ddb1fd1"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("877ff3bf-364b-4c4d-95d9-3b26fe96a71c"),
                            Email = "Player10@gmail.com",
                            Name = "Player 10 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("3ab5d4c6-adc2-439e-8993-24dbc82cbb7e"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("8e38eb16-ff9f-4139-b4a3-c6dbce3be47c"),
                            Email = "Player11@gmail.com",
                            Name = "Player 11 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("dfd73943-b654-48fd-8d3f-bc35a2fcf19e"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("495f9e98-8cd4-4497-9208-88310e7c5b14"),
                            Email = "Player12@gmail.com",
                            Name = "Player 12 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("3ab5d4c6-adc2-439e-8993-24dbc82cbb7e"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("99743438-2088-4925-acd5-265d63c85b2f"),
                            Email = "Player13@gmail.com",
                            Name = "Player 13 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("3ed94c61-a398-47d6-9c82-641b1ddb1fd1"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("f5dda917-d742-4bb3-8ea1-21f6aaabbd45"),
                            Email = "Player14@gmail.com",
                            Name = "Player 14 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("dfd73943-b654-48fd-8d3f-bc35a2fcf19e"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("b6af14b2-0dbb-43a7-8e9a-a539912f57e3"),
                            Email = "Player15@gmail.com",
                            Name = "Player 15 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("3ab5d4c6-adc2-439e-8993-24dbc82cbb7e"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("7fa52e62-50d4-4088-9562-fb4eda62a9b1"),
                            Email = "Player16@gmail.com",
                            Name = "Player 16 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("3ed94c61-a398-47d6-9c82-641b1ddb1fd1"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("93ca263f-6c4e-484b-8336-5385eb2dcd0a"),
                            Email = "Player17@gmail.com",
                            Name = "Player 17 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("3ed94c61-a398-47d6-9c82-641b1ddb1fd1"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("3d53a60f-5bdc-4700-9fcc-f363705ad4ac"),
                            Email = "Player18@gmail.com",
                            Name = "Player 18 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("3ab5d4c6-adc2-439e-8993-24dbc82cbb7e"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("e546d23f-b2cc-4167-aa2c-66a4da078bb4"),
                            Email = "Player19@gmail.com",
                            Name = "Player 19 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("3ab5d4c6-adc2-439e-8993-24dbc82cbb7e"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("7cfa5b86-70bb-4099-b97d-7919fb5f7c18"),
                            Email = "Player20@gmail.com",
                            Name = "Player 20 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("3ab5d4c6-adc2-439e-8993-24dbc82cbb7e"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("08fed487-2a97-40c6-b21a-bdeaa7612cba"),
                            Email = "Player21@gmail.com",
                            Name = "Player 21 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("dfd73943-b654-48fd-8d3f-bc35a2fcf19e"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("3ae935c2-f9e7-420f-be99-8301fcab9add"),
                            Email = "Player22@gmail.com",
                            Name = "Player 22 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("3ed94c61-a398-47d6-9c82-641b1ddb1fd1"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("142606dc-9dcd-41f9-9367-a39df5e15c6c"),
                            Email = "Player23@gmail.com",
                            Name = "Player 23 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("3ab5d4c6-adc2-439e-8993-24dbc82cbb7e"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("f684e40c-5181-43b2-9309-7cc765b8a466"),
                            Email = "Player24@gmail.com",
                            Name = "Player 24 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("dfd73943-b654-48fd-8d3f-bc35a2fcf19e"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("bd8b2277-68b8-46b6-86f2-3a70b47c29ca"),
                            Email = "Player25@gmail.com",
                            Name = "Player 25 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("3ab5d4c6-adc2-439e-8993-24dbc82cbb7e"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("bd6b3108-1531-4b12-a8dd-7f2bec441932"),
                            Email = "Player26@gmail.com",
                            Name = "Player 26 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("dfd73943-b654-48fd-8d3f-bc35a2fcf19e"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("151a6aa7-7519-4453-9407-ba9a89015e40"),
                            Email = "Player27@gmail.com",
                            Name = "Player 27 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("3ed94c61-a398-47d6-9c82-641b1ddb1fd1"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("85ef4d4d-53c7-4f2f-9678-6eb021977119"),
                            Email = "Player28@gmail.com",
                            Name = "Player 28 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("3ab5d4c6-adc2-439e-8993-24dbc82cbb7e"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("ee864b8d-a21a-425c-97e5-5d4f85542fdf"),
                            Email = "Player29@gmail.com",
                            Name = "Player 29 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("dfd73943-b654-48fd-8d3f-bc35a2fcf19e"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("2a038187-b81f-4c20-bd09-729ac6622a44"),
                            Email = "Player30@gmail.com",
                            Name = "Player 30 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("dfd73943-b654-48fd-8d3f-bc35a2fcf19e"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("70ab142d-9b19-4bc9-af58-cc98d7a5d3f4"),
                            Email = "Player31@gmail.com",
                            Name = "Player 31 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("3ab5d4c6-adc2-439e-8993-24dbc82cbb7e"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("e7759c16-e36d-4979-a293-9e274ed12c83"),
                            Email = "Player32@gmail.com",
                            Name = "Player 32 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("3ed94c61-a398-47d6-9c82-641b1ddb1fd1"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("f91c73ed-f9ed-4fdc-b571-6ba9c9d799d3"),
                            Email = "Player33@gmail.com",
                            Name = "Player 33 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("dfd73943-b654-48fd-8d3f-bc35a2fcf19e"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("b50606f7-c4b0-4583-9cc6-0b5be9ad4e93"),
                            Email = "Player34@gmail.com",
                            Name = "Player 34 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("dfd73943-b654-48fd-8d3f-bc35a2fcf19e"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("20bbdda5-3946-48eb-8a95-53ab0094e9c5"),
                            Email = "Player35@gmail.com",
                            Name = "Player 35 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("dfd73943-b654-48fd-8d3f-bc35a2fcf19e"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("62527bf4-484f-4072-8aea-be05109e3065"),
                            Email = "Player36@gmail.com",
                            Name = "Player 36 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("3ed94c61-a398-47d6-9c82-641b1ddb1fd1"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("c6f24529-f267-418f-bafa-b3849f0f0372"),
                            Email = "Player37@gmail.com",
                            Name = "Player 37 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("3ed94c61-a398-47d6-9c82-641b1ddb1fd1"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("02dd50b1-3b03-4f22-88e6-935bbc262566"),
                            Email = "Player38@gmail.com",
                            Name = "Player 38 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("3ed94c61-a398-47d6-9c82-641b1ddb1fd1"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("f3ab0a49-fe30-4bc9-9b04-f1f083459f82"),
                            Email = "Player39@gmail.com",
                            Name = "Player 39 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("3ed94c61-a398-47d6-9c82-641b1ddb1fd1"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("ed3cbf44-4edd-48ce-ac80-eae3756249fd"),
                            Email = "Player40@gmail.com",
                            Name = "Player 40 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("3ed94c61-a398-47d6-9c82-641b1ddb1fd1"),
                            Role = "user"
                        });
                });

            modelBuilder.Entity("ApiMySql.Data.Entities.Users.User", b =>
                {
                    b.HasOne("ApiMySql.Data.Entities.Positions.Position", "Position")
                        .WithMany("Users")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
