// <auto-generated />
using System;
using ApiGladsGo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ApiGladsGo.Migrations
{
    [DbContext(typeof(ApiGladsGoContext))]
    partial class ApiGladsGoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1");

            modelBuilder.Entity("ApiMySql.Data.Entities.Positions.Position", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(80);

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(4);

                    b.HasKey("Id");

                    b.ToTable("Positions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5862b9b3-8f24-4bbc-82d7-00afa904f2a5"),
                            Name = "Wide Reciver",
                            ShortName = "WR"
                        },
                        new
                        {
                            Id = new Guid("b527b14b-a0cf-4763-b64f-07ec482cc784"),
                            Name = "Quarterback",
                            ShortName = "QB"
                        },
                        new
                        {
                            Id = new Guid("2a99cbf7-04c5-42d9-bf46-66ec8abb6bac"),
                            Name = "Running Back",
                            ShortName = "RB"
                        });
                });

            modelBuilder.Entity("ApiMySql.Data.Entities.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT")
                        .HasMaxLength(80);

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(80);

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(20);

                    b.Property<Guid>("PositionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PositionId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9d5e1cf5-9a36-4fd2-b2af-d14371591873"),
                            Email = "Player1@gmail.com",
                            Name = "Player 1 ",
                            Password = "adm",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("5862b9b3-8f24-4bbc-82d7-00afa904f2a5"),
                            Role = "adm"
                        },
                        new
                        {
                            Id = new Guid("d8be9f87-562b-4ea5-9265-302985090bb2"),
                            Email = "Player2@gmail.com",
                            Name = "Player 2 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("b527b14b-a0cf-4763-b64f-07ec482cc784"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("db903e18-c74a-40af-b2a9-76877d7c7f41"),
                            Email = "Player3@gmail.com",
                            Name = "Player 3 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("2a99cbf7-04c5-42d9-bf46-66ec8abb6bac"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("9d65417c-18ae-4a55-be13-de1ac984db14"),
                            Email = "Player4@gmail.com",
                            Name = "Player 4 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("2a99cbf7-04c5-42d9-bf46-66ec8abb6bac"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("2711a363-26cc-4524-a26a-faaa8b897c4a"),
                            Email = "Player5@gmail.com",
                            Name = "Player 5 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("2a99cbf7-04c5-42d9-bf46-66ec8abb6bac"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("a9f8a52e-4ad6-4c64-8d2b-f5b6839c0c3a"),
                            Email = "Player6@gmail.com",
                            Name = "Player 6 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("b527b14b-a0cf-4763-b64f-07ec482cc784"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("14f8a9c6-5012-490c-bceb-eb831fa605f3"),
                            Email = "Player7@gmail.com",
                            Name = "Player 7 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("b527b14b-a0cf-4763-b64f-07ec482cc784"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("8399da38-27a6-4562-ae9a-ee42b6531ab8"),
                            Email = "Player8@gmail.com",
                            Name = "Player 8 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("b527b14b-a0cf-4763-b64f-07ec482cc784"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("4013dfd4-1402-4ac7-9066-de3ac2481ee7"),
                            Email = "Player9@gmail.com",
                            Name = "Player 9 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("b527b14b-a0cf-4763-b64f-07ec482cc784"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("1d3038ab-448f-46f0-9d69-1ab41315c606"),
                            Email = "Player10@gmail.com",
                            Name = "Player 10 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("5862b9b3-8f24-4bbc-82d7-00afa904f2a5"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("003df1db-07af-4154-9ea9-b6f86e167e0c"),
                            Email = "Player11@gmail.com",
                            Name = "Player 11 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("2a99cbf7-04c5-42d9-bf46-66ec8abb6bac"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("ed406918-c48f-44f3-a897-5680214c834b"),
                            Email = "Player12@gmail.com",
                            Name = "Player 12 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("5862b9b3-8f24-4bbc-82d7-00afa904f2a5"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("7c300731-4db7-4f4c-8362-c524f42166a4"),
                            Email = "Player13@gmail.com",
                            Name = "Player 13 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("b527b14b-a0cf-4763-b64f-07ec482cc784"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("ed9248c3-f85a-4645-bb82-00f0d709be33"),
                            Email = "Player14@gmail.com",
                            Name = "Player 14 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("2a99cbf7-04c5-42d9-bf46-66ec8abb6bac"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("81d0e316-c80b-4f04-b040-4c13ddf48d0d"),
                            Email = "Player15@gmail.com",
                            Name = "Player 15 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("5862b9b3-8f24-4bbc-82d7-00afa904f2a5"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("cead14cd-fb29-497f-8f6d-4c88ac7a13cd"),
                            Email = "Player16@gmail.com",
                            Name = "Player 16 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("b527b14b-a0cf-4763-b64f-07ec482cc784"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("d6ea5435-244f-42c5-aa7f-83f89a52094e"),
                            Email = "Player17@gmail.com",
                            Name = "Player 17 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("b527b14b-a0cf-4763-b64f-07ec482cc784"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("c2473cd5-3f80-4e63-8d5e-69b5ccc6ff5f"),
                            Email = "Player18@gmail.com",
                            Name = "Player 18 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("5862b9b3-8f24-4bbc-82d7-00afa904f2a5"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("f8bfdc52-5b3b-48d2-a4c6-67ec57af0688"),
                            Email = "Player19@gmail.com",
                            Name = "Player 19 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("5862b9b3-8f24-4bbc-82d7-00afa904f2a5"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("d456b25e-1a2d-4292-b973-c2c8e83fd953"),
                            Email = "Player20@gmail.com",
                            Name = "Player 20 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("5862b9b3-8f24-4bbc-82d7-00afa904f2a5"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("81967380-5645-4ac4-9dce-61c22ad88af7"),
                            Email = "Player21@gmail.com",
                            Name = "Player 21 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("2a99cbf7-04c5-42d9-bf46-66ec8abb6bac"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("ac44cdb9-8d06-44a1-a2e9-fccd8d863de3"),
                            Email = "Player22@gmail.com",
                            Name = "Player 22 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("b527b14b-a0cf-4763-b64f-07ec482cc784"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("c4451c94-571b-4a90-9eb5-1423a0bda09e"),
                            Email = "Player23@gmail.com",
                            Name = "Player 23 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("5862b9b3-8f24-4bbc-82d7-00afa904f2a5"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("08f800e2-5b87-4daa-806e-dcf86b9fe949"),
                            Email = "Player24@gmail.com",
                            Name = "Player 24 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("2a99cbf7-04c5-42d9-bf46-66ec8abb6bac"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("be9d6e0a-8139-4fdc-bfe5-156aedaef122"),
                            Email = "Player25@gmail.com",
                            Name = "Player 25 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("5862b9b3-8f24-4bbc-82d7-00afa904f2a5"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("4e6f0e09-3b47-4dbe-a93d-9e852a549d6a"),
                            Email = "Player26@gmail.com",
                            Name = "Player 26 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("2a99cbf7-04c5-42d9-bf46-66ec8abb6bac"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("7ebf64ef-af0a-40bd-98d3-80912346144a"),
                            Email = "Player27@gmail.com",
                            Name = "Player 27 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("b527b14b-a0cf-4763-b64f-07ec482cc784"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("47004ae1-999e-4d1d-91f0-4f3e1a5e9da7"),
                            Email = "Player28@gmail.com",
                            Name = "Player 28 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("5862b9b3-8f24-4bbc-82d7-00afa904f2a5"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("4048c397-f514-4ea1-82dd-9e9800e815e1"),
                            Email = "Player29@gmail.com",
                            Name = "Player 29 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("2a99cbf7-04c5-42d9-bf46-66ec8abb6bac"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("f6c47ff7-335a-40f5-b431-af0a58b2b9e6"),
                            Email = "Player30@gmail.com",
                            Name = "Player 30 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("2a99cbf7-04c5-42d9-bf46-66ec8abb6bac"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("42c28349-53e3-4194-9614-50dd655474da"),
                            Email = "Player31@gmail.com",
                            Name = "Player 31 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("5862b9b3-8f24-4bbc-82d7-00afa904f2a5"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("0da3f550-d95f-43b4-b11a-07358b635c7d"),
                            Email = "Player32@gmail.com",
                            Name = "Player 32 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("b527b14b-a0cf-4763-b64f-07ec482cc784"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("15985f12-f0d5-43aa-b6ed-0aa3f55714ca"),
                            Email = "Player33@gmail.com",
                            Name = "Player 33 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("2a99cbf7-04c5-42d9-bf46-66ec8abb6bac"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("1aae7de9-266d-4e51-926b-a07be092c743"),
                            Email = "Player34@gmail.com",
                            Name = "Player 34 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("2a99cbf7-04c5-42d9-bf46-66ec8abb6bac"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("a0c3c58b-845d-47ac-9e97-f848e7c506c8"),
                            Email = "Player35@gmail.com",
                            Name = "Player 35 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("2a99cbf7-04c5-42d9-bf46-66ec8abb6bac"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("adcd730c-2af4-42c0-80ec-b7652619a30a"),
                            Email = "Player36@gmail.com",
                            Name = "Player 36 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("b527b14b-a0cf-4763-b64f-07ec482cc784"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("186aedc4-b738-44b1-97a6-11c0a751163d"),
                            Email = "Player37@gmail.com",
                            Name = "Player 37 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("b527b14b-a0cf-4763-b64f-07ec482cc784"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("4a24c058-1389-45f9-829c-dbc124929668"),
                            Email = "Player38@gmail.com",
                            Name = "Player 38 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("b527b14b-a0cf-4763-b64f-07ec482cc784"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("e8f78da0-c114-43fc-bec7-86b043bb48b7"),
                            Email = "Player39@gmail.com",
                            Name = "Player 39 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("b527b14b-a0cf-4763-b64f-07ec482cc784"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("c89b5b89-30fe-48eb-9bf6-bb923800e791"),
                            Email = "Player40@gmail.com",
                            Name = "Player 40 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("b527b14b-a0cf-4763-b64f-07ec482cc784"),
                            Role = "user"
                        });
                });

            modelBuilder.Entity("ApiMySql.Data.Entities.Users.User", b =>
                {
                    b.HasOne("ApiMySql.Data.Entities.Positions.Position", "Position")
                        .WithMany("Users")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
