// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechWeekFatecSul.Data;

namespace TechWeekFatecSul.Migrations
{
    [DbContext(typeof(TechWeekFatecSulContext))]
    partial class TechWeekFatecSulContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1");

            modelBuilder.Entity("ApiMySql.Data.Entities.Positions.Position", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(80);

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(4);

                    b.HasKey("Id");

                    b.ToTable("Positions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4f6c0760-3487-4b35-a04a-d559a534f51b"),
                            Name = "Wide Reciver",
                            ShortName = "WR"
                        },
                        new
                        {
                            Id = new Guid("b04304f2-391e-415d-98a4-4d79057e8c60"),
                            Name = "Quarterback",
                            ShortName = "QB"
                        },
                        new
                        {
                            Id = new Guid("294140b3-0f39-49fd-9160-16856a975c6b"),
                            Name = "Running Back",
                            ShortName = "RB"
                        });
                });

            modelBuilder.Entity("ApiMySql.Data.Entities.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT")
                        .HasMaxLength(80);

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(80);

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(20);

                    b.Property<Guid>("PositionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PositionId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d3f1a843-3f26-4ee5-8e11-5826a0dc57d1"),
                            Email = "Player1@gmail.com",
                            Name = "Player 1 ",
                            Password = "adm",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("4f6c0760-3487-4b35-a04a-d559a534f51b"),
                            Role = "adm"
                        },
                        new
                        {
                            Id = new Guid("aa9d9ab1-146c-44f9-b923-fb1e7dd89160"),
                            Email = "Player2@gmail.com",
                            Name = "Player 2 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("b04304f2-391e-415d-98a4-4d79057e8c60"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("92d292e7-05e0-43ba-b377-ed5b4c88cca1"),
                            Email = "Player3@gmail.com",
                            Name = "Player 3 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("294140b3-0f39-49fd-9160-16856a975c6b"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("90e14dee-e677-4869-9869-a4a01154ce18"),
                            Email = "Player4@gmail.com",
                            Name = "Player 4 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("294140b3-0f39-49fd-9160-16856a975c6b"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("54875180-9122-4825-9bfe-a102b7653cfd"),
                            Email = "Player5@gmail.com",
                            Name = "Player 5 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("294140b3-0f39-49fd-9160-16856a975c6b"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("408a9b1b-6a63-4ba1-978f-136d146fb77e"),
                            Email = "Player6@gmail.com",
                            Name = "Player 6 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("b04304f2-391e-415d-98a4-4d79057e8c60"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("b271f1ef-5113-4e33-b5f4-18141fd45632"),
                            Email = "Player7@gmail.com",
                            Name = "Player 7 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("b04304f2-391e-415d-98a4-4d79057e8c60"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("95326ec0-f70a-4bc4-9121-3fbc8a2a2ab7"),
                            Email = "Player8@gmail.com",
                            Name = "Player 8 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("b04304f2-391e-415d-98a4-4d79057e8c60"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("a48ba5bb-20b9-4616-8d21-78744db8c5e4"),
                            Email = "Player9@gmail.com",
                            Name = "Player 9 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("b04304f2-391e-415d-98a4-4d79057e8c60"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("c2748a63-2445-4366-af48-31d957ddcbef"),
                            Email = "Player10@gmail.com",
                            Name = "Player 10 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("4f6c0760-3487-4b35-a04a-d559a534f51b"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("acdcc1d4-9bbf-477f-93ce-01b65470ec2e"),
                            Email = "Player11@gmail.com",
                            Name = "Player 11 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("294140b3-0f39-49fd-9160-16856a975c6b"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("dd5dac2b-ed5d-4086-8c1a-f933d7a7cb1a"),
                            Email = "Player12@gmail.com",
                            Name = "Player 12 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("4f6c0760-3487-4b35-a04a-d559a534f51b"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("9b0a3902-90cf-4ce9-8a31-165c57bd4ba5"),
                            Email = "Player13@gmail.com",
                            Name = "Player 13 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("b04304f2-391e-415d-98a4-4d79057e8c60"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("247acd77-95e5-48ea-83b5-ebc250dfe304"),
                            Email = "Player14@gmail.com",
                            Name = "Player 14 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("294140b3-0f39-49fd-9160-16856a975c6b"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("fe0b1c93-482d-44c0-95c0-af7ed7221d0e"),
                            Email = "Player15@gmail.com",
                            Name = "Player 15 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("4f6c0760-3487-4b35-a04a-d559a534f51b"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("7eba9a7b-696f-4af6-8a6d-1e6b99dba9c5"),
                            Email = "Player16@gmail.com",
                            Name = "Player 16 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("b04304f2-391e-415d-98a4-4d79057e8c60"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("cc500e6c-e73b-446e-bf4c-22e1e5bdb798"),
                            Email = "Player17@gmail.com",
                            Name = "Player 17 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("b04304f2-391e-415d-98a4-4d79057e8c60"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("6af444e3-b7cb-4313-8023-4a63c60caf3c"),
                            Email = "Player18@gmail.com",
                            Name = "Player 18 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("4f6c0760-3487-4b35-a04a-d559a534f51b"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("b65d4603-5227-4b2e-8376-89cd0e7cf796"),
                            Email = "Player19@gmail.com",
                            Name = "Player 19 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("4f6c0760-3487-4b35-a04a-d559a534f51b"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("ee7d24eb-a2b9-4ef5-b59a-b8b3f20267fd"),
                            Email = "Player20@gmail.com",
                            Name = "Player 20 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("4f6c0760-3487-4b35-a04a-d559a534f51b"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("52ea50ca-0aaf-429b-9319-afd8495ed046"),
                            Email = "Player21@gmail.com",
                            Name = "Player 21 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("294140b3-0f39-49fd-9160-16856a975c6b"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("d3f1f268-7210-401e-bb8f-fc7bed310b7f"),
                            Email = "Player22@gmail.com",
                            Name = "Player 22 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("b04304f2-391e-415d-98a4-4d79057e8c60"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("b3a0ec5c-7e7d-4342-8b54-d259852deaa9"),
                            Email = "Player23@gmail.com",
                            Name = "Player 23 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("4f6c0760-3487-4b35-a04a-d559a534f51b"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("85f29c08-0b6a-491e-a068-ab40f8e6268a"),
                            Email = "Player24@gmail.com",
                            Name = "Player 24 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("294140b3-0f39-49fd-9160-16856a975c6b"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("d4f34070-6f45-4c92-aed8-a6dbbad14bb4"),
                            Email = "Player25@gmail.com",
                            Name = "Player 25 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("4f6c0760-3487-4b35-a04a-d559a534f51b"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("d8037002-3a6a-42ff-878f-ee12ae67bf72"),
                            Email = "Player26@gmail.com",
                            Name = "Player 26 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("294140b3-0f39-49fd-9160-16856a975c6b"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("d114b214-3c3d-4678-843e-874401c6a7ac"),
                            Email = "Player27@gmail.com",
                            Name = "Player 27 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("b04304f2-391e-415d-98a4-4d79057e8c60"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("7364cf35-41c1-40a2-80dd-87ecbfa2f3ec"),
                            Email = "Player28@gmail.com",
                            Name = "Player 28 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("4f6c0760-3487-4b35-a04a-d559a534f51b"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("3867fc7a-7e67-4b9e-8bbc-20c05520742c"),
                            Email = "Player29@gmail.com",
                            Name = "Player 29 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("294140b3-0f39-49fd-9160-16856a975c6b"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("c844f890-8a6b-48fa-8c78-b7d64efa3812"),
                            Email = "Player30@gmail.com",
                            Name = "Player 30 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("294140b3-0f39-49fd-9160-16856a975c6b"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("7024774d-f6a9-420c-a99e-2670c912dce1"),
                            Email = "Player31@gmail.com",
                            Name = "Player 31 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("4f6c0760-3487-4b35-a04a-d559a534f51b"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("7163f8bc-aafa-4b3d-81d8-f1158759fdd6"),
                            Email = "Player32@gmail.com",
                            Name = "Player 32 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("b04304f2-391e-415d-98a4-4d79057e8c60"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("5681cdba-d364-40bf-a748-45026c7f7487"),
                            Email = "Player33@gmail.com",
                            Name = "Player 33 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("294140b3-0f39-49fd-9160-16856a975c6b"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("9192580f-8ac2-48ae-a285-ecdaa9b37f2e"),
                            Email = "Player34@gmail.com",
                            Name = "Player 34 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("294140b3-0f39-49fd-9160-16856a975c6b"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("8e2a7813-4d67-43cd-94bf-bd6bc0e2f4b2"),
                            Email = "Player35@gmail.com",
                            Name = "Player 35 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("294140b3-0f39-49fd-9160-16856a975c6b"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("a3c10012-4545-4e95-9fe1-194978e64198"),
                            Email = "Player36@gmail.com",
                            Name = "Player 36 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("b04304f2-391e-415d-98a4-4d79057e8c60"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("5ccb9a8b-5b36-4a86-9148-3144232df979"),
                            Email = "Player37@gmail.com",
                            Name = "Player 37 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("b04304f2-391e-415d-98a4-4d79057e8c60"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("3b182ca5-7ae1-46eb-b69e-ba29c69ad21a"),
                            Email = "Player38@gmail.com",
                            Name = "Player 38 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("b04304f2-391e-415d-98a4-4d79057e8c60"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("10dfd9a6-ed04-46df-bc57-43b13e396ec4"),
                            Email = "Player39@gmail.com",
                            Name = "Player 39 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("b04304f2-391e-415d-98a4-4d79057e8c60"),
                            Role = "user"
                        },
                        new
                        {
                            Id = new Guid("34356936-69fc-4ece-ad74-ad9ffeb48a76"),
                            Email = "Player40@gmail.com",
                            Name = "Player 40 ",
                            Password = "user",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("b04304f2-391e-415d-98a4-4d79057e8c60"),
                            Role = "user"
                        });
                });

            modelBuilder.Entity("ApiMySql.Data.Entities.Users.User", b =>
                {
                    b.HasOne("ApiMySql.Data.Entities.Positions.Position", "Position")
                        .WithMany("Users")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
