// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechWeekFatecSul.Data;

namespace TechWeekFatecSul.Migrations
{
    [DbContext(typeof(TechWeekFatecSulContext))]
    partial class TechWeekFatecSulContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1");

            modelBuilder.Entity("ApiMySql.Data.Entities.Positions.Position", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(80);

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(4);

                    b.HasKey("Id");

                    b.ToTable("Positions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f9126193-54cc-4dba-b092-2a1c09bc1ee8"),
                            Name = "Wide Reciver",
                            ShortName = "WR"
                        },
                        new
                        {
                            Id = new Guid("39bf2ee4-97ad-47ba-8faf-fe2cdfcb34c3"),
                            Name = "Quarterback",
                            ShortName = "QB"
                        },
                        new
                        {
                            Id = new Guid("607bee02-237e-4e29-bfcd-22324f405348"),
                            Name = "Running Back",
                            ShortName = "RB"
                        });
                });

            modelBuilder.Entity("ApiMySql.Data.Entities.SystemUsers.SystemUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT")
                        .HasMaxLength(80);

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(80);

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(20);

                    b.Property<Guid>("PositionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PositionId");

                    b.ToTable("SystemUsers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bec7c4d4-7b9d-43be-9486-d330df7eecb3"),
                            Email = "Player1@gmail.com",
                            Name = "Player 1 ",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("f9126193-54cc-4dba-b092-2a1c09bc1ee8")
                        },
                        new
                        {
                            Id = new Guid("ce10cb70-fd07-40cd-91b0-eca67b605ec8"),
                            Email = "Player2@gmail.com",
                            Name = "Player 2 ",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("39bf2ee4-97ad-47ba-8faf-fe2cdfcb34c3")
                        },
                        new
                        {
                            Id = new Guid("1059b6c7-fe0f-47f3-abd8-8fb28fc7d5d2"),
                            Email = "Player3@gmail.com",
                            Name = "Player 3 ",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("607bee02-237e-4e29-bfcd-22324f405348")
                        },
                        new
                        {
                            Id = new Guid("fe74cef3-2b3d-4c25-81a8-c53554a0c772"),
                            Email = "Player4@gmail.com",
                            Name = "Player 4 ",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("607bee02-237e-4e29-bfcd-22324f405348")
                        },
                        new
                        {
                            Id = new Guid("7cf2f0cc-a141-40c4-81f3-82851c20f958"),
                            Email = "Player5@gmail.com",
                            Name = "Player 5 ",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("607bee02-237e-4e29-bfcd-22324f405348")
                        },
                        new
                        {
                            Id = new Guid("e15c412c-124c-455a-a7d6-700fed1a326e"),
                            Email = "Player6@gmail.com",
                            Name = "Player 6 ",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("39bf2ee4-97ad-47ba-8faf-fe2cdfcb34c3")
                        },
                        new
                        {
                            Id = new Guid("9528147b-d960-471c-a1ee-e84bd2e58268"),
                            Email = "Player7@gmail.com",
                            Name = "Player 7 ",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("39bf2ee4-97ad-47ba-8faf-fe2cdfcb34c3")
                        },
                        new
                        {
                            Id = new Guid("5c28c14e-8785-436c-b036-de3ce5cf7474"),
                            Email = "Player8@gmail.com",
                            Name = "Player 8 ",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("39bf2ee4-97ad-47ba-8faf-fe2cdfcb34c3")
                        },
                        new
                        {
                            Id = new Guid("6bd5dfc4-9306-4ce1-b94e-c434abe65366"),
                            Email = "Player9@gmail.com",
                            Name = "Player 9 ",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("39bf2ee4-97ad-47ba-8faf-fe2cdfcb34c3")
                        },
                        new
                        {
                            Id = new Guid("d6a6120b-1051-4b3f-8e0c-c5eb4ee7c210"),
                            Email = "Player10@gmail.com",
                            Name = "Player 10 ",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("f9126193-54cc-4dba-b092-2a1c09bc1ee8")
                        },
                        new
                        {
                            Id = new Guid("eebec909-89d7-4744-8a7a-fc421345307a"),
                            Email = "Player11@gmail.com",
                            Name = "Player 11 ",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("607bee02-237e-4e29-bfcd-22324f405348")
                        },
                        new
                        {
                            Id = new Guid("ba6cb9f9-ffd5-4f07-9a4f-9895289a409a"),
                            Email = "Player12@gmail.com",
                            Name = "Player 12 ",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("f9126193-54cc-4dba-b092-2a1c09bc1ee8")
                        },
                        new
                        {
                            Id = new Guid("b2f3d679-8596-49bd-abea-6b9abac0dade"),
                            Email = "Player13@gmail.com",
                            Name = "Player 13 ",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("39bf2ee4-97ad-47ba-8faf-fe2cdfcb34c3")
                        },
                        new
                        {
                            Id = new Guid("114ce200-bdb2-4bac-b71d-b464de2bd962"),
                            Email = "Player14@gmail.com",
                            Name = "Player 14 ",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("607bee02-237e-4e29-bfcd-22324f405348")
                        },
                        new
                        {
                            Id = new Guid("ac4b15ba-f19e-4cc1-930c-fb9a5160ade5"),
                            Email = "Player15@gmail.com",
                            Name = "Player 15 ",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("f9126193-54cc-4dba-b092-2a1c09bc1ee8")
                        },
                        new
                        {
                            Id = new Guid("a66ae7f2-dc58-421e-9bc2-464e1f4d1056"),
                            Email = "Player16@gmail.com",
                            Name = "Player 16 ",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("39bf2ee4-97ad-47ba-8faf-fe2cdfcb34c3")
                        },
                        new
                        {
                            Id = new Guid("fda6cf1d-af6c-435a-9c35-a779b00d4e2c"),
                            Email = "Player17@gmail.com",
                            Name = "Player 17 ",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("39bf2ee4-97ad-47ba-8faf-fe2cdfcb34c3")
                        },
                        new
                        {
                            Id = new Guid("8e02c517-6972-45e5-a33a-06fa9eba3a88"),
                            Email = "Player18@gmail.com",
                            Name = "Player 18 ",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("f9126193-54cc-4dba-b092-2a1c09bc1ee8")
                        },
                        new
                        {
                            Id = new Guid("57fdb557-ec63-4533-aed6-b29141952bae"),
                            Email = "Player19@gmail.com",
                            Name = "Player 19 ",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("f9126193-54cc-4dba-b092-2a1c09bc1ee8")
                        },
                        new
                        {
                            Id = new Guid("ee576ed2-4ef5-466c-971c-d685ce80265c"),
                            Email = "Player20@gmail.com",
                            Name = "Player 20 ",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("f9126193-54cc-4dba-b092-2a1c09bc1ee8")
                        },
                        new
                        {
                            Id = new Guid("871ecaaf-5b4d-4732-95cb-c6cbb810bd44"),
                            Email = "Player21@gmail.com",
                            Name = "Player 21 ",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("607bee02-237e-4e29-bfcd-22324f405348")
                        },
                        new
                        {
                            Id = new Guid("303a9550-517c-4300-92cd-2a673ddfa286"),
                            Email = "Player22@gmail.com",
                            Name = "Player 22 ",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("39bf2ee4-97ad-47ba-8faf-fe2cdfcb34c3")
                        },
                        new
                        {
                            Id = new Guid("7c9b7685-a1b3-4ab9-a310-fb1df53bc128"),
                            Email = "Player23@gmail.com",
                            Name = "Player 23 ",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("f9126193-54cc-4dba-b092-2a1c09bc1ee8")
                        },
                        new
                        {
                            Id = new Guid("a7348a99-7595-4fb0-a729-899cfdace166"),
                            Email = "Player24@gmail.com",
                            Name = "Player 24 ",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("607bee02-237e-4e29-bfcd-22324f405348")
                        },
                        new
                        {
                            Id = new Guid("9d34bc8d-9d85-4c48-8b01-33f9f313d6ab"),
                            Email = "Player25@gmail.com",
                            Name = "Player 25 ",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("f9126193-54cc-4dba-b092-2a1c09bc1ee8")
                        },
                        new
                        {
                            Id = new Guid("5916064d-5da6-40d7-afe4-c74439209b4e"),
                            Email = "Player26@gmail.com",
                            Name = "Player 26 ",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("607bee02-237e-4e29-bfcd-22324f405348")
                        },
                        new
                        {
                            Id = new Guid("90a44f03-ddbd-4ff4-9676-fe866253361f"),
                            Email = "Player27@gmail.com",
                            Name = "Player 27 ",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("39bf2ee4-97ad-47ba-8faf-fe2cdfcb34c3")
                        },
                        new
                        {
                            Id = new Guid("b505d4a7-c66e-4a6f-b2d7-8fef8f9689da"),
                            Email = "Player28@gmail.com",
                            Name = "Player 28 ",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("f9126193-54cc-4dba-b092-2a1c09bc1ee8")
                        },
                        new
                        {
                            Id = new Guid("1e48887d-a0bf-4ac8-843c-c7394cd29081"),
                            Email = "Player29@gmail.com",
                            Name = "Player 29 ",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("607bee02-237e-4e29-bfcd-22324f405348")
                        },
                        new
                        {
                            Id = new Guid("c549a547-edc3-421d-94ea-2c13293172a9"),
                            Email = "Player30@gmail.com",
                            Name = "Player 30 ",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("607bee02-237e-4e29-bfcd-22324f405348")
                        },
                        new
                        {
                            Id = new Guid("7824c8fa-4c5b-45b5-bba8-2c9cc7983a01"),
                            Email = "Player31@gmail.com",
                            Name = "Player 31 ",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("f9126193-54cc-4dba-b092-2a1c09bc1ee8")
                        },
                        new
                        {
                            Id = new Guid("698dc34d-c663-473c-926c-8b930c130998"),
                            Email = "Player32@gmail.com",
                            Name = "Player 32 ",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("39bf2ee4-97ad-47ba-8faf-fe2cdfcb34c3")
                        },
                        new
                        {
                            Id = new Guid("ba517172-a21f-46e1-bb94-5f35f8d1831a"),
                            Email = "Player33@gmail.com",
                            Name = "Player 33 ",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("607bee02-237e-4e29-bfcd-22324f405348")
                        },
                        new
                        {
                            Id = new Guid("bf15e88d-f089-4c7b-9e09-26f011f9ff9b"),
                            Email = "Player34@gmail.com",
                            Name = "Player 34 ",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("607bee02-237e-4e29-bfcd-22324f405348")
                        },
                        new
                        {
                            Id = new Guid("d8ff9499-32f0-466b-b9c4-891b861d2a92"),
                            Email = "Player35@gmail.com",
                            Name = "Player 35 ",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("607bee02-237e-4e29-bfcd-22324f405348")
                        },
                        new
                        {
                            Id = new Guid("2c237f4f-fa8a-47f4-b9bd-76bb6a50dbdc"),
                            Email = "Player36@gmail.com",
                            Name = "Player 36 ",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("39bf2ee4-97ad-47ba-8faf-fe2cdfcb34c3")
                        },
                        new
                        {
                            Id = new Guid("8cb94908-e3ab-4719-9993-40aa8034cab6"),
                            Email = "Player37@gmail.com",
                            Name = "Player 37 ",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("39bf2ee4-97ad-47ba-8faf-fe2cdfcb34c3")
                        },
                        new
                        {
                            Id = new Guid("79307878-0d15-4590-b80b-93eecdf1664d"),
                            Email = "Player38@gmail.com",
                            Name = "Player 38 ",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("39bf2ee4-97ad-47ba-8faf-fe2cdfcb34c3")
                        },
                        new
                        {
                            Id = new Guid("2d9af057-bf4b-4300-bc62-ffbdd4d25fcd"),
                            Email = "Player39@gmail.com",
                            Name = "Player 39 ",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("39bf2ee4-97ad-47ba-8faf-fe2cdfcb34c3")
                        },
                        new
                        {
                            Id = new Guid("c26779fa-c5e0-40ca-8b20-de754fae81a7"),
                            Email = "Player40@gmail.com",
                            Name = "Player 40 ",
                            Phone = "(47) 99630-5948",
                            PositionId = new Guid("39bf2ee4-97ad-47ba-8faf-fe2cdfcb34c3")
                        });
                });

            modelBuilder.Entity("ApiMySql.Data.Entities.SystemUsers.SystemUser", b =>
                {
                    b.HasOne("ApiMySql.Data.Entities.Positions.Position", "Position")
                        .WithMany("SystemUsers")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
